# Generated by Django 5.0.3 on 2024-08-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('measure', models.CharField(choices=[('OZ', 'ounces'), ('GM', 'grams'), ('L', 'liters'), ('LB', 'pounds'), ('CUP', 'cups'), ('DR', 'drams')], default='ounces', max_length=20)),
            ],
        ),
    ]
