# Generated by Django 5.0.3 on 2024-08-23 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_entry_date_updated_topic_date_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='entry',
            new_name='topic',
        ),
    ]
