# Generated by Django 5.0.3 on 2024-09-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_rename_entry_entry_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='text',
            new_name='entry',
        ),
    ]
