# Generated by Django 5.0.3 on 2024-09-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_rename_text_entry_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry',
            field=models.TextField(blank=True, default=1, null=True),
        ),
    ]
